/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.InventorySupplyAdminJPanel;

import HealthCareManager.PartnerInfirmaries.PartnerInfirmiries;
import IntegrationSystem.HealthcareSystemOrganizationIntegration;
import IntegrationSystem.HealthCareSystemEnterprise;
import InventorySupply.InventorySupply;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Rishi
 */
public class InventorySupplyAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    HealthcareSystemOrganizationIntegration medicalServiceCentralisationEcoSystem;
    InventorySupply inventorySupply;    
    public InventorySupplyAdminJPanel(JPanel userProcessContainer,HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration, InventorySupply medSupWarehouse) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.medicalServiceCentralisationEcoSystem = healthcareSystemOrganizationIntegration;
        this.inventorySupply = medSupWarehouse;
        jPanel1.setVisible(false);
   
    }
    
    public void populateTree(){
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MedSuppliesButton = new javax.swing.JButton();
        OrderManagementButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new java.awt.BorderLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 70, 169));
        jPanel2.setPreferredSize(new java.awt.Dimension(1720, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedSuppliesButton.setBackground(new java.awt.Color(0, 70, 169));
        MedSuppliesButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MedSuppliesButton.setText("Medical Supplies Data");
        MedSuppliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedSuppliesButtonActionPerformed(evt);
            }
        });
        jPanel2.add(MedSuppliesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 401, -1));

        OrderManagementButton.setBackground(new java.awt.Color(0, 70, 169));
        OrderManagementButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OrderManagementButton.setText("Order Management");
        OrderManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderManagementButtonActionPerformed(evt);
            }
        });
        jPanel2.add(OrderManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 401, -1));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void OrderManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderManagementButtonActionPerformed
        InventorySupplyDispatchData medSupWarehouseOrderDatabase = new InventorySupplyDispatchData(userProcessContainer,medicalServiceCentralisationEcoSystem, inventorySupply);
        userProcessContainer.add("medSupWarehouseOrderDatabase",medSupWarehouseOrderDatabase);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medSupWarehouseOrderDatabase");
    }//GEN-LAST:event_OrderManagementButtonActionPerformed

    private void MedSuppliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedSuppliesButtonActionPerformed

        InventoryStockData medSupWarehouseDatabase = new InventoryStockData(userProcessContainer,medicalServiceCentralisationEcoSystem, inventorySupply);
        userProcessContainer.add("medSupWarehouseDatabase",medSupWarehouseDatabase);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"medSupWarehouseDatabase");
    }//GEN-LAST:event_MedSuppliesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MedSuppliesButton;
    private javax.swing.JButton OrderManagementButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
