/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.InventorySupplyAdminJPanel;


import Model.DispatcherServiceProvider.DispatcherService;
import Model.DispatcherServiceProvider.DispatcherServiceDirectory;
import IntegrationSystem.HealthcareSystemOrganizationIntegration;
import IntegrationSystem.ConsumerRecords;
import IntegrationSystem.EnterpriseUserDirectory;
import InventorySupply.InventorySupply;
import InventorySupply.InventorySupplyModelDirectory;
import InventorySupply.Dipatches.DispatchRequest;
import InventorySupply.Dipatches.OrderDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishi
 */
public class InventorySupplyDispatchData extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration;
    ConsumerRecords userAccount;
    EnterpriseUserDirectory userAccountDirectory;
    InventorySupplyModelDirectory inventorySupplyModelDirectory;
    InventorySupply inventorySupply;
    
    public InventorySupplyDispatchData(JPanel userProcessContainer , HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration, InventorySupply inventorySupply) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.healthcareSystemOrganizationIntegration = healthcareSystemOrganizationIntegration;
        this.inventorySupply = inventorySupply;
        
        insertRecordsInJTable();
        updateDispatcher();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header2 = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AssignButton = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        Header1 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNewOrders = new javax.swing.JTable();
        jLabelDeliveryAgency = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        ItemToggle = new javax.swing.JComboBox<>();
        jLabelQuantity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 70, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Header2.setForeground(new java.awt.Color(255, 255, 255));
        Header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header2.setText("Orders List");
        add(Header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 706, -1));

        jButtonHome.setBackground(new java.awt.Color(0, 70, 169));
        jButtonHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        UpdateButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        AssignButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        AssignButton.setText("ASSIGN");
        AssignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignButtonActionPerformed(evt);
            }
        });
        add(AssignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 120, 40));

        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelName.setText("Instrument Name :");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 180, -1));

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 270, -1));

        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPrice.setText("Instrument Price :");
        add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, 20));

        Header1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Header1.setForeground(new java.awt.Color(255, 255, 255));
        Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header1.setText("Medical Supplies Orders");
        add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 940, -1));

        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });
        add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 270, -1));

        jTableNewOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Medical Equipment Names", "Medical Equipment Total Price", "Hospital ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNewOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 680, 110));

        jLabelDeliveryAgency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeliveryAgency.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDeliveryAgency.setText("Delivery Agency");
        add(jLabelDeliveryAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        jTextFieldQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantityActionPerformed(evt);
            }
        });
        add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 270, -1));

        ItemToggle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ItemToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, -1, -1));

        jLabelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelQuantity.setText("Quantity :");
        add(jLabelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void AssignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableNewOrders.getModel();
        int selected_row_ix = jTableNewOrders.getSelectedRow();
        DispatchRequest order = (DispatchRequest) model.getValueAt(selected_row_ix, 0);
        String delivery_agency_id = (String) ItemToggle.getSelectedItem();
        order.setTransporter_Id(delivery_agency_id);
        
    }//GEN-LAST:event_AssignButtonActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignButton;
    private javax.swing.JLabel Header1;
    private javax.swing.JLabel Header2;
    private javax.swing.JComboBox<String> ItemToggle;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JLabel jLabelDeliveryAgency;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNewOrders;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        jTextFieldName.setText("");
        jTextFieldPrice.setText("");
        jTextFieldQuantity.setText("");
    }

    private void insertRecordsInJTable() {
        
        OrderDirectory orderDirectory = inventorySupply.getOrderDirectory();
        ArrayList<DispatchRequest> orderList = orderDirectory.getOrderList();
        DefaultTableModel model = (DefaultTableModel) jTableNewOrders.getModel();
        model.setRowCount(0);

        
        for(DispatchRequest order: orderList)
        {
            if(order.getRequest_processing_status().equals("new")){
                model.addRow(new Object[]{order, order.getFirstAidKitsTotalQuantity(), order.getRequested_supply_Amount(),order.getInventory_Id()});
            }
        }
        jTableNewOrders.setModel(model);
    }

    private void updateDispatcher() {
        DispatcherServiceDirectory deliveryAgencyDirectory = healthcareSystemOrganizationIntegration.getDispatcherServiceDirectory();
        ArrayList<DispatcherService> dispatcherServices = deliveryAgencyDirectory.getDeliveryAgencyList();
        for(DispatcherService deliveryAgency: dispatcherServices){
            ItemToggle.addItem(deliveryAgency.getDeliveryAgencyId());
        }
    }
}
