/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthCareManager.InventorySupplyProviderJPanel;

import HealthCareManager.PartnerInfirmaries.PartnerInfirmiries;
import IntegrationSystem.HealthcareSystemOrganizationIntegration;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishi
 */

public class ConsultantAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedSupAdminWorkAreaJPanel
     */
    JPanel JPanelProcessRender;
    HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration;
    PartnerInfirmiries partnerInfirmiries;
    public ConsultantAdminPanel(JPanel userProcessContainer,HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration, PartnerInfirmiries infirmiries) {
        initComponents();
        this.JPanelProcessRender = userProcessContainer;
        this.healthcareSystemOrganizationIntegration = healthcareSystemOrganizationIntegration;
        this.partnerInfirmiries = infirmiries;
        jPanel1.setVisible(false);
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonTestDatabase = new javax.swing.JButton();
        jButtonPlaceOrder = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 70, 169));
        jPanel2.setPreferredSize(new java.awt.Dimension(1720, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTestDatabase.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTestDatabase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonTestDatabase.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTestDatabase.setText("Medical Supplies Database");
        jButtonTestDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestDatabaseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTestDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 387, 430, 70));

        jButtonPlaceOrder.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlaceOrder.setText("Place Order");
        jButtonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceOrderActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 477, 430, 70));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1833, 1102));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceOrderActionPerformed
        InventoryRequestCart inventoryRequestCart = new InventoryRequestCart(JPanelProcessRender,healthcareSystemOrganizationIntegration, partnerInfirmiries);
        JPanelProcessRender.add("inventoryRequestCart",inventoryRequestCart);
        CardLayout cardLayout = (CardLayout) JPanelProcessRender.getLayout();
        cardLayout.show(JPanelProcessRender,"inventoryRequestCart");
    }//GEN-LAST:event_jButtonPlaceOrderActionPerformed

    private void jButtonTestDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestDatabaseActionPerformed

        InventorySupplyDataPanel inventorySupplyDataPanel = new InventorySupplyDataPanel(JPanelProcessRender,healthcareSystemOrganizationIntegration, partnerInfirmiries);
        JPanelProcessRender.add("inventorySupplyDataPanel",inventorySupplyDataPanel);
        CardLayout cardLayout = (CardLayout) JPanelProcessRender.getLayout();
        cardLayout.show(JPanelProcessRender,"inventorySupplyDataPanel");
    }//GEN-LAST:event_jButtonTestDatabaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlaceOrder;
    private javax.swing.JButton jButtonTestDatabase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
