/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminRole.PracticeAdminJPanel;


import HealthCareManager.PartnerInfirmaries.PartnerInfirmiries;
import IntegrationSystem.HealthcareSystemOrganizationIntegration;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author harshithnarahari
 */
public class PartnerInfirmariesAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration;
    PartnerInfirmiries infirmiries;
    public PartnerInfirmariesAdminJPanel(JPanel userProcessContainer,HealthcareSystemOrganizationIntegration infirmarymgmtEcosystem, PartnerInfirmiries infirmaries) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.healthcareSystemOrganizationIntegration = infirmarymgmtEcosystem;
        this.infirmiries = infirmaries;
        jPanel1.setVisible(false);
        populateTree();
    }
    
    public void populateTree(){
        //DefaultTreeModel model=(DefaultTreeModel)Admin.getModel();
       // Add the code for draw your system structure shown by JTree
       
      //  model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        MedTechnicalAccountsPageButton = new javax.swing.JButton();
        AdministrativeAccountsPageButton = new javax.swing.JButton();
        OperationalAccountsPageButton = new javax.swing.JButton();
        MedSuppliesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1720, 1080));
        setLayout(new java.awt.BorderLayout());

        jSplitPane.setPreferredSize(new java.awt.Dimension(1720, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1720, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MedTechnicalAccountsPageButton.setBackground(new java.awt.Color(228, 238, 247));
        MedTechnicalAccountsPageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedTechnicalAccountsPageButton.setText("Technical & Lab Testing");
        MedTechnicalAccountsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedTechnicalAccountsPageButtonActionPerformed(evt);
            }
        });
        jPanel2.add(MedTechnicalAccountsPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 220, 30));

        AdministrativeAccountsPageButton.setBackground(new java.awt.Color(228, 238, 247));
        AdministrativeAccountsPageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdministrativeAccountsPageButton.setText("Admin & Accounting ");
        AdministrativeAccountsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrativeAccountsPageButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AdministrativeAccountsPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 220, 30));

        OperationalAccountsPageButton.setBackground(new java.awt.Color(228, 238, 247));
        OperationalAccountsPageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OperationalAccountsPageButton.setText("Operational Team");
        OperationalAccountsPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationalAccountsPageButtonActionPerformed(evt);
            }
        });
        jPanel2.add(OperationalAccountsPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, 30));

        MedSuppliesButton.setBackground(new java.awt.Color(228, 238, 247));
        MedSuppliesButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MedSuppliesButton.setText("Medical Supplies Admin");
        MedSuppliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedSuppliesButtonActionPerformed(evt);
            }
        });
        jPanel2.add(MedSuppliesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/R1601C_VILLINSKI.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 890));

        jSplitPane.setRightComponent(jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane.setLeftComponent(jPanel1);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void MedTechnicalAccountsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedTechnicalAccountsPageButtonActionPerformed
        // TODO add your handling code here:
        ServiceTeamAccountsJPanel medTechnicalAccountsPage = new ServiceTeamAccountsJPanel(userProcessContainer,healthcareSystemOrganizationIntegration, infirmiries);
        userProcessContainer.add("MedTechnicalAccountsPage",medTechnicalAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"MedTechnicalAccountsPage");
    }//GEN-LAST:event_MedTechnicalAccountsPageButtonActionPerformed

    private void AdministrativeAccountsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrativeAccountsPageButtonActionPerformed
        
        PractitionerDataJPanel administrativeAccountsPage = new PractitionerDataJPanel(userProcessContainer,healthcareSystemOrganizationIntegration, infirmiries);
        userProcessContainer.add("AdministrativeAccountsPage",administrativeAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"AdministrativeAccountsPage");
    }//GEN-LAST:event_AdministrativeAccountsPageButtonActionPerformed

    private void OperationalAccountsPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationalAccountsPageButtonActionPerformed
        ManagerAccountsJPanel operationalAccountsPage = new ManagerAccountsJPanel(userProcessContainer,healthcareSystemOrganizationIntegration, infirmiries);
        userProcessContainer.add("OperationalAccountsPage",operationalAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"OperationalAccountsPage");
    }//GEN-LAST:event_OperationalAccountsPageButtonActionPerformed

    private void MedSuppliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedSuppliesButtonActionPerformed
        // TODO add your handling code here:
        SupplyStoreAdminJPanel medSupAdminAccountsPage= new SupplyStoreAdminJPanel(userProcessContainer,healthcareSystemOrganizationIntegration, infirmiries);
        userProcessContainer.add("MedSupAdminAccountsPage",medSupAdminAccountsPage);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.show(userProcessContainer,"MedSupAdminAccountsPage");
        
    }//GEN-LAST:event_MedSuppliesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministrativeAccountsPageButton;
    private javax.swing.JButton MedSuppliesButton;
    private javax.swing.JButton MedTechnicalAccountsPageButton;
    private javax.swing.JButton OperationalAccountsPageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
