/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HealthCareManager.FirstResponderJPanel;


import HealthCareManager.PartnerInfirmaries.PartnerInfirmiries;
import HealthCareManager.Consultation.Consultation;
import HealthCareManager.Consultation.ConsultationTestResults;
import IntegrationSystem.HealthcareSystemOrganizationIntegration;
import IntegrationSystem.ConsumerRecords;
import IntegrationSystem.EnterpriseUserDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishi
 */
public class FRConsultationData extends javax.swing.JPanel {

    /**
     * Creates new form OperationalAccountsPage
     */
    JPanel userProcessContainer;
    HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration;
    ConsumerRecords consumers;
    EnterpriseUserDirectory enterpriseUserDirectory;
    ConsultationTestResults consultationTestResults;
    PartnerInfirmiries infirmiries;
    public FRConsultationData(JPanel userProcessContainer , HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration, PartnerInfirmiries infirmiries) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.healthcareSystemOrganizationIntegration = healthcareSystemOrganizationIntegration;
        this.infirmiries = infirmiries;
        if(infirmiries.getLabTestDirectory()== null)
           infirmiries.setLabTestDirectory(new ConsultationTestResults());
        InsertDataToJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButtonTestCreate = new javax.swing.JButton();
        jButtonUpdateTest = new javax.swing.JButton();
        jButtonDeleteTest = new javax.swing.JButton();
        jLabelTestname = new javax.swing.JLabel();
        jTextFieldTestsName = new javax.swing.JTextField();
        jLabelTestPrice = new javax.swing.JLabel();
        jLabelHeaders = new javax.swing.JLabel();
        jTextFieldTestingPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 70, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("All Examination");
        add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 706, -1));

        jButtonExit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 40));

        jButtonTestCreate.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTestCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonTestCreate.setText("CREATE");
        jButtonTestCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestCreateActionPerformed(evt);
            }
        });
        add(jButtonTestCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, 30));

        jButtonUpdateTest.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUpdateTest.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonUpdateTest.setText("UPDATE");
        add(jButtonUpdateTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, -1, 30));

        jButtonDeleteTest.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteTest.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonDeleteTest.setText("DELETE");
        add(jButtonDeleteTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 100, 30));

        jLabelTestname.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabelTestname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTestname.setText("Lab Test Name");
        add(jLabelTestname, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 400, 140, 30));

        jTextFieldTestsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestsNameActionPerformed(evt);
            }
        });
        add(jTextFieldTestsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 240, 30));

        jLabelTestPrice.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabelTestPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTestPrice.setText("Testing Price");
        add(jLabelTestPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 100, 30));

        jLabelHeaders.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelHeaders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeaders.setText("Hospital Test Database");
        add(jLabelHeaders, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 706, -1));

        jTextFieldTestingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTestingPriceActionPerformed(evt);
            }
        });
        add(jTextFieldTestingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 240, 30));

        jTableTestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Test Name", "Testing Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 430, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/Medi (1) (1).jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1490, 940));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldTestsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestsNameActionPerformed

    private void jTextFieldTestingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTestingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTestingPriceActionPerformed

    private void jButtonTestCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestCreateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableTestTable.getModel();
        ConsultationTestResults consultationTestResults = infirmiries.getLabTestDirectory();
        Consultation consultation = new Consultation();
        String test_name = jTextFieldTestsName.getText();
        String test_price = jTextFieldTestingPrice.getText();
        consultation.setTest_name(test_name);
        consultation.setTest_price(test_price);
        consultationTestResults.addTest(consultation);
        infirmiries.setLabTestDirectory(consultationTestResults);
        JOptionPane.showMessageDialog(this, "New Test Information has been added.");
        model.addRow(new Object[]{consultation,consultation.getTest_price()});
        remove_empty_input_Values();
    }//GEN-LAST:event_jButtonTestCreateActionPerformed
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteTest;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonTestCreate;
    private javax.swing.JButton jButtonUpdateTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHeaders;
    private javax.swing.JLabel jLabelTestPrice;
    private javax.swing.JLabel jLabelTestname;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTestTable;
    private javax.swing.JTextField jTextFieldTestingPrice;
    private javax.swing.JTextField jTextFieldTestsName;
    // End of variables declaration//GEN-END:variables

    private void remove_empty_input_Values() {
        jTextFieldTestsName.setText("");
        jTextFieldTestingPrice.setText("");
    }

    private void InsertDataToJTable() {
        
        consultationTestResults = infirmiries.getLabTestDirectory();
        ArrayList<Consultation> consultationsReports = consultationTestResults.getTest_results_List();
        DefaultTableModel model = (DefaultTableModel) jTableTestTable.getModel();
        model.setRowCount(0);
        
        for(Consultation consultation: consultationsReports)
        {
            model.addRow(new Object[]{consultation, consultation.getTest_price()});

        }
        jTableTestTable.setModel(model);
    }
}
