/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminRole.AdminJPanel;



import IntegrationSystem.HealthcareSystemOrganizationIntegration;


import HealthCareMainSystem.AdminRoles.InventoryManagerRole;
import InventorySupply.InventorySupply;
import InventorySupply.InventorySupplyModelDirectory;
import IntegrationSystem.ConsumerRecords;
import IntegrationSystem.EnterpriseUserDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karthik 
 */
public class FirstAidSupplyInventoryRecordsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstAidSupplyInventoryRecordsJPanel
     */
    JPanel processExecutionPanel;
    HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration;
    InventorySupplyModelDirectory inventorySupplyModelDirectory;
    ConsumerRecords consumerAccount;
    EnterpriseUserDirectory UserAccountDirectory;

    public FirstAidSupplyInventoryRecordsJPanel(JPanel userProcessContainer , HealthcareSystemOrganizationIntegration healthcareSystemOrganizationIntegration) {
        
        this.processExecutionPanel = userProcessContainer;
        this.healthcareSystemOrganizationIntegration = healthcareSystemOrganizationIntegration;
        initComponents();
        if(healthcareSystemOrganizationIntegration.getInventoryDirectory()== null)
           healthcareSystemOrganizationIntegration.setInventoryDirectory(new InventorySupplyModelDirectory());
       
        addDefaultvalues();
        InsertDataToJTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        CreateButton = new javax.swing.JButton();
        jTextName = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jTextPassword = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 70, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Medical Warehouse Data");
        add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 832, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Warehouse ID", "Warehouse Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 787, 110));

        CreateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CreateButton.setText("CREATE");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });
        add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 110, 50));
        add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 351, 30));

        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 110, 50));

        jLabelPassword.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabelPassword.setText("Password :");
        add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, -1));

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });
        add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 351, 26));

        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });
        add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 351, -1));

        jLabelID.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabelID.setText("ID :");
        add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 150, -1));

        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 100, 50));

        jLabelName.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabelName.setText("Warehouse Name :");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/COVID-19-Palliative-1-1200x800 (1).jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1630, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) processExecutionPanel.getLayout();
            crdLyt.show(processExecutionPanel,"Sysadmin");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableEmployee.getModel();
        ArrayList<String> user_input = check_empty_field();
        inventorySupplyModelDirectory = healthcareSystemOrganizationIntegration.getInventoryDirectory();
        EnterpriseUserDirectory enterpriseUsers = healthcareSystemOrganizationIntegration.getUserAccDirectory();
        if(enterpriseUsers.verifyUserUnique(user_input.get(0))){
            
            
            consumerAccount = new ConsumerRecords(user_input.get(0), user_input.get(2), new InventoryManagerRole());
            
            InventorySupply inventorySupply = new InventorySupply(user_input.get(0), user_input.get(1));
            consumerAccount.setInventory_Supply(inventorySupply);
            inventorySupplyModelDirectory.addMedSupWarehouse(inventorySupply);
            
            enterpriseUsers.addConsumerData(consumerAccount);
            
            JOptionPane.showMessageDialog(this, "New Inventory supply data has been added.");
            model.addRow(new Object[]{consumerAccount,user_input.get(1),user_input.get(2)});
            remove_empty_input_Values();
        }
        else{
            JOptionPane.showMessageDialog(this, "Username already taken. Please use a new name.");
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int selected_row_ix = jTableEmployee.getSelectedRow();

        if(selected_row_ix < 0){
            JOptionPane.showMessageDialog(this, "Please select rows before updating");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) jTableEmployee.getModel();
        ConsumerRecords consumer_acc_selected = (ConsumerRecords)model.getValueAt(selected_row_ix, 0);        
        UserAccountDirectory = healthcareSystemOrganizationIntegration.getUserAccDirectory();
        inventorySupplyModelDirectory = healthcareSystemOrganizationIntegration.getInventoryDirectory();
        ArrayList<ConsumerRecords> consumerRecordses = UserAccountDirectory.get_User_Details();
        for(ConsumerRecords userAcc: consumerRecordses)
        {
            if(userAcc.getEmail_Id().equals(consumer_acc_selected.getEmail_Id()))
            {
                InventorySupply inventorySupply = userAcc.getInventory_Supply();
                ArrayList<String> user_input = check_empty_field();
                model.setValueAt(user_input.get(1), selected_row_ix, 1);
                model.setValueAt(user_input.get(2), selected_row_ix, 2);
                inventorySupplyModelDirectory.updateMedSupWarehouse(user_input, inventorySupply);
                UserAccountDirectory.updateEnterpriseUser(set_user_input_values(userAcc, user_input));
                break;
            }
        }
        JOptionPane.showMessageDialog(this, "Updated Data");

        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selected_row_ix = jTableEmployee.getSelectedRow();

        if(selected_row_ix < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTableEmployee.getModel();
        ConsumerRecords select_user_account_details = (ConsumerRecords)model.getValueAt(selected_row_ix, 0);
        UserAccountDirectory = healthcareSystemOrganizationIntegration.getUserAccDirectory();
        InventorySupply inventorySupply = select_user_account_details.getInventory_Supply();
        inventorySupplyModelDirectory.deleteMedSupWarehouse(inventorySupply);
        UserAccountDirectory.removeConsumerRecord(select_user_account_details);
        model.removeRow(selected_row_ix);
        InsertDataToJTable();
        remove_empty_input_Values();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jTableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeMouseClicked
        // TODO add your handling code here:
        CreateButton.setEnabled(false);
        int selected_row_ix = jTableEmployee.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableEmployee.getModel();
        ConsumerRecords get_selected_details = (ConsumerRecords)model.getValueAt(selected_row_ix, 0);
        jTextID.setEditable(false);
        jTextID.setText(get_selected_details.getEmail_Id());
        jTextName.setText(get_selected_details.getInventory_Supply().getInventory_Location_Name());
        jTextPassword.setText(get_selected_details.getPassword());
        
    }//GEN-LAST:event_jTableEmployeeMouseClicked
    private ConsumerRecords set_user_input_values(ConsumerRecords consumer, ArrayList<String> user_input) {
//        consumerAccount.getEmployee().setEmployee_id(user_input.get(0));
        consumer.getInventory_Supply().setInventory_Location_Name(user_input.get(1));
        consumer.setPassword(user_input.get(2));
        return consumer;
    }
    private void remove_empty_input_Values(){
        jTextID.setText("");
        jTextName.setText("");
        jTextPassword.setText("");
    }
    
    public ArrayList<String> check_empty_field(){
        ArrayList<String> user_input = new ArrayList<>();
        String user_emp_id = jTextID.getText();
        String user_emp_name = jTextName.getText();
        String user_password = jTextPassword.getText();

        
        if(user_emp_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "User ID can't be left empty.");
        }
        else if(user_emp_name.isEmpty()){
            JOptionPane.showMessageDialog(this, "User Name can't be left empty.");
        }
        else if(user_password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a Password.");
        }
        
        
        user_input.add(user_emp_id);
        user_input.add(user_emp_name);
        user_input.add(user_password);
        
        return user_input;
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel Header;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPassword;
    // End of variables declaration//GEN-END:variables

    
    private void InsertDataToJTable() {
        EnterpriseUserDirectory userAccountDirectory = healthcareSystemOrganizationIntegration.getUserAccDirectory();
        ArrayList<ConsumerRecords> usersList = userAccountDirectory.get_User_Details();
    
        DefaultTableModel model = (DefaultTableModel) jTableEmployee.getModel();
        model.setRowCount(0);
        for(ConsumerRecords userAccount: usersList)
        {   
            if(userAccount.getRole().toString() == "MedSupWarehouseAdmin"){
                model.addRow(new Object[]{userAccount,userAccount.getInventory_Supply().getInventory_Location_Name(),userAccount.getPassword()});
            }
            
        }
        
        jTableEmployee.setModel(model);
    }

    private void addDefaultvalues() {
        
        EnterpriseUserDirectory usersList = healthcareSystemOrganizationIntegration.getUserAccDirectory();
        consumerAccount = new ConsumerRecords("inventoryAccess", "password",new InventoryManagerRole());
        InventorySupply inventorySupply = new InventorySupply("inventoryAccess","Inventory");
        inventorySupplyModelDirectory = healthcareSystemOrganizationIntegration.getInventoryDirectory();
        inventorySupplyModelDirectory.addMedSupWarehouse(inventorySupply);
        consumerAccount.setInventory_Supply(inventorySupply);
        if(usersList.verifyUserUnique("inventoryAccess")){
            usersList.addConsumerData(consumerAccount);
        }
           
    }
    
}
